### ISSUE TITLE
Updating to support 1.7.7+

### ISSUE THREAD

**Issue by SteveYurka** [awslabs/dynamodb-transactions#16]
Someone else has already created this issue, however there is in response (from may last year).

Is this currently planning to be updated?

The Java SDK has added a fair few features (that make dynamodb specifically worthwhile when comparing them to other databases), such as documents and other types, all which are unusable

**Comment by mirceal** [comment]
https://github.com/awslabs/dynamodb-transactions/pull/18/files

**Comment by johnnyw-aws** [comment]
https://github.com/awslabs/dynamodb-transactions/commit/6b1ca283ac878f405561a1fba278753e89c89812
