### ISSUE TITLE
Allow put/update to overwrite previous delete

### ISSUE THREAD

**Issue by atorstling** [awslabs/dynamodb-transactions#23]
Hi!

It is currently forbidden to perform multiple writes against the same item in the same transaction. For our application logic, however, It would be handy if it would be allowed to delete an item and insert a new version of it in the same transaction. Otherwise we would have to figure out in the app which deletes and adds are actually correlated and translate them into updates, which quickly gets messy, especially since we're using the mapper. 

I've made an experimental change in TransactionItem::addRequestToMap which allows the insertion to go through if `existingRequest instanceof Request.DeleteItem && (request instanceof Request.PutItem ||
                                      request instanceof Request.UpdateItem)`. This seems to work fine. 

What do you think? Is this a sufficient change for this feature and is it a good idea at all?

**Comment by Yanacek** [comment]
Hey @atorstling , I realize this request is several years old at this point, so a response might not be particularly helpful. Anyway, there's additional complexity about making sure that the original item image was backed up, and won't be replaced by another write on top of it. It's certainly possible to get this to work, but it would require quite a bit of thought, and plenty more testing, to make sure that rollback always works correctly. 

So the feature request is reasonable, but it's a tricky and risky enough change that we should wait to get a sense for how much demand there is for the feature before going forward. For example, looking back, I wish that there were some features that we didn't include originally, like the ability to resume a transaction on a different transaction manager and proceed with it. The feature seemed applicable to one use case, but ended up adding more complexity to the library than it was worth.

**Comment by atorstling** [comment]
Hey @Yanacek . The current behaviour actually the same as in SQL Server. SQL Server delays index updates until transaction end, which means that removing and inserting again creates index clashes with the removed item. If you google for that problem, I'm sure you'll find quite a few people struggling. When I bumped into it, it required us to rework our entire bulk update process. 

So anecdotally I think this problem is one of those problems which people put a lot of effort into working around, but aren't so vocal about. They just accept it as a fact. I just want to say that if your stance is to wait for feature requests. I don't think they will be coming in at a fantastic rate. But I do think that this is a problem for many.

Anyway, thanks for considering and answering, and thanks for a good product!
