### ISSUE TITLE
Working with DynamoDBMapper

### ISSUE THREAD

**Issue by nykolaslima** [awslabs/dynamodb-transactions#24]
In order to use transactions we need to instantiate `PutItemRequest` and configure all attributes.
Is there any way to use transactions with `DynamoDBMapper`?

**Comment by johnnyw-aws** [comment]
Here are a few examples of using transactions with the DynamoDBMapper:
https://github.com/awslabs/dynamodb-transactions/blob/master/examples/src/main/java/com/amazonaws/services/dynamodbv2/transactions/examples/TransactionExamples.java#L450

Currently, delete, load and save are supported:
https://github.com/awslabs/dynamodb-transactions/blob/master/src/main/java/com/amazonaws/services/dynamodbv2/transactions/Transaction.java#L1420

**Comment by surbhin** [comment]
Hi, for my project we also need query and scan. Any specific reason these arent there yet?

**Comment by Yanacek** [comment]
Query and scan inside of transactions are very tricky in this model. The transaction library only locks individual items, not ranges of items. Query and Scan can involve an infinite number of items in any range, so unfortunately supporting those would require pretty much a redesign and rewrite of the whole library. However, there are static helper functions in Transaction.java that you can use on any item you get from DynamoDB outside of a transaction to ensure that the items you get back from a scan or a query are valid.

Another approach for Query is to make a table with the same schema as the table you're querying, but without a range key (same hash key, no range key). Your transaction would perform a GetItem on that corresponding dummy item before you perform your query outside of the transaction library. If your transaction doesn't commit, you throw away your query results. This approach locks the entire range for that hash key, so it could result in a bunch of contention depending on your access pattern, but it could work.
