### ISSUE TITLE
Plans for Ruby SDK support?

### ISSUE THREAD

**Issue by ngordon17** [awslabs/dynamodb-transactions#25]
Do you have plans to port this library for the AWS Ruby SDK?

**Comment by agaur-aws** [comment]
@ngordon17  we currently don't have any plans on our roadmap to port this library to Ruby. Is using the library through jruby an option you can explore?

**Comment by ngordon17** [comment]
We could potentially do that, although it would be much easier if Ruby was supported natively.

Given that there are no plans I will close this issue.
