### ISSUE TITLE
Upgrade to 400 Kb item limit?

### ISSUE THREAD

**Issue by PGWelch** [awslabs/dynamodb-transactions#26]
The docs say transactions are limited to 64 Kb - e.g. https://github.com/awslabs/dynamodb-transactions/blob/master/DESIGN.md

As Amazon now supports 400 Kb items, are 400 Kb transactions supported (I.e. Dynamodb-transactions Docs need updating) or does the library need updating to support 400 Kb items in transactions?

**Comment by draukadin** [comment]
Transactions use a record in a DDB table to manage all the items participating in the transaction.  The record size is independent of this library.  I don't recall if the SDK enforces the limit or not so an older SDK might check the record size and throw an exception is the size is > 64Kb while a new one will do it for > 400Kb.

So just a docs updating is required.

**Comment by Yanacek** [comment]
That's right - 400 KB items are supported, and there is an integration test to support that claim. The doc update was just merged into master.
