### ISSUE TITLE
Isolation Levels - Clarification

### ISSUE THREAD

**Issue by MrDevZero** [awslabs/dynamodb-transactions#28]
I'm utilizing the DynamoDB Transaction Library and studying the "IsolationLevel" enum to get a better understanding of how to perform isolated reads. Looking for documentation on the 3 available isolation levels but can't find anything online:
- UNCOMMITTED
- COMMITTED
- READ_LOCK

For anyone familiar with these IsolationLevels an explanation or a link to appropriate documentation would be much appreciated!   I have 3 Dynamo tables each of which will always be updated within a single transaction using the TransactionManager and I'm looking to read the state of a collection of items from all 3 tables post-transaction.

**Comment by Yanacek** [comment]
@MrDevZero , did you see the description of the isolation levels in https://github.com/awslabs/dynamodb-transactions/blob/master/DESIGN.md ? 

In short:
* READ_LOCK: the reads are done inside of a transaction, so no other transaction can touch these items (even for read) until your transaction commits (and if they do, your transaction could be rolled back)
* COMMITTED: only a known committed version of the item will be returned. There could be a transaction in progress for the item, and if that is the case, the library will go read the backed up item image for the current transaction.
* UNCOMMITTED: this is sort of the "wild west" of reads, and I would be very careful with it. You might read a copy of an item that will never be committed. That is, the returned item could be involved in a transaction that will be rolled back before it's ever committed.
