### ISSUE TITLE
TransactionAssertionException exception without any description

### ISSUE THREAD

**Issue by Pushapgl** [awslabs/dynamodb-transactions#33]
com.amazonaws.services.dynamodbv2.transactions.exceptions.TransactionAssertionException: Item should not have been applied.  Unable to release lock - item - {}, 

I recently started getting the TransactionAssertionException and I didn't find any documentation when do we receive this error? Can some please let me know if this is transient or some permanent  
 exception.

**Comment by Yanacek** [comment]
Closing as it appears to be fixed, but feel free to re-open or file a fresh issue if you find otherwise.
