### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by davidgoate** [awslabs/dynamodb-transactions#41]
We were interested in using this but there are a few concerns/questions we have:

1. Is this project still active (there are a couple of PR's that are a few months old and some issues as old as 2015 that are unaddressed). Also no major commits in almost a year and a half.
1. Why isn't this published to Maven central to make dependency management more simple than shipping around JARs or building from source.
1. This looked promising but it's from 2013 https://aws.amazon.com/blogs/aws/dynamodb-transaction-library/ I haven't come across anything yet that indicates this library has been officially deprecated but it doesn't look to be particularly active or showing signs of having a roadmap.

Appreciate the work that's gone into this, just would be nice to have a clearer picture to help us assess whether it's appropriate for us moving forwards. 

Thanks.

**Comment by dmavrikakis** [comment]
Judging by the lack of response to this and previous threads I am inclined to believe that this project is not active. I am also wondering if it's sensible to incorporate this into a project.

I have not yet found an alternative to handling transactions, there appears to be no documentation (up-to-date) on the AWS website that indicates an alternative. So that leaves me thinking that our only option is to design a structure that is not dependent on transactions.

Have you had any luck in finding solution?

**Comment by davidgoate** [comment]
@dmavrikakis sadly I have also had no joy on finding an alternative solution.

It's a shame as on the surface, i.e. just googling and finding the AWS blog talking about transaction support and referencing this library it indicates to the casual observer that such features would be well supported.

**Comment by davidgoate** [comment]
@Yanacek Sorry if you're the wrong person to ask. I saw that you recently commented on another issue in this repo for maven central upload. Can you provide any information on this?

**Comment by pegerto** [comment]
@davidgoate 

This project has been a reference for a few years,  what I think is missing from Dynamo is to have a mechanism for a logged batch, similar to what Cassandra offers.
The implementation of this library go a bit further,  I will not use this project if I really need ACID. 

Ultimately in my case, the use of the library is in response to an unexpected change at the API I expect  I will remove this library from the use case as soon we can rework the data model.

**Comment by Yanacek** [comment]
In terms of the current status of the project, we'll fix (and accept bugfixes), and keep it compatible with the latest Java SDK versions, but don't have plans to implement significant features or port the library to other languages.

**Comment by davidgoate** [comment]
Although it's closed, for anyone who finds this in future it seems transaction support has been added to the core feature set: https://aws.amazon.com/blogs/aws/new-amazon-dynamodb-transactions/
