### ISSUE TITLE
Does this library provide encryption?

### ISSUE THREAD

**Issue by shawncaojob** [awslabs/dynamodb-transactions#42]
db mapper can encrypt object by giving a "provider" when creating it.
but it seems that this library is not using dbmapper.

Thanks,

**Comment by draukadin** [comment]
It uses the dbMapper in the [transaction manager](https://github.com/awslabs/dynamodb-transactions/blob/master/src/main/java/com/amazonaws/services/dynamodbv2/transactions/TransactionManager.java#L109).  It is just that the transaction manger will build the mapper for you and doesn't provide a way to inject your own mapper.

**Comment by Yanacek** [comment]
@shawncaojob , have you tried configuring the transaction library to use the encryption manager? How did it go?
