### ISSUE TITLE
boto3 python version?

### ISSUE THREAD

**Issue by wobeng** [awslabs/dynamodb-transactions#45]
Hi

Any chances that there will be a boto3 python version?

**Comment by Yanacek** [comment]
I don't know of anything currently in the works, but there are a couple of Python transaction libraries out there. I haven't used either to know what they're like, but I found a couple here: http://dynamodb-mapper.readthedocs.io/en/latest/ and here: https://github.com/drblez/dynamodb-transaction-manager
