### ISSUE TITLE
dynamodb transaction Manager under Javascript  SDK

### ISSUE THREAD

**Issue by dmitrirussu** [awslabs/dynamodb-transactions#47]
Hi, I would like to know if already exist TransactionManager for dynamodb under aws-sdk for JavaScript?
Thanks
https://github.com/awslabs/dynamodb-transactions/blob/a3e9f25844cf9097cd9447fbf07e8820cfa12ff4/examples/src/main/java/com/amazonaws/services/dynamodbv2/transactions/examples/TransactionExamples.java#L103

**Comment by Yanacek** [comment]
This library is not ported to JavaScript. However, fortunately DynamoDB now supports transactions in the service, so you don't need to rely on complicated libraries like this any more! (And the transactions APIs are supported by the regular AWS SDK for JavaScript.) Take a look at https://aws.amazon.com/blogs/aws/new-amazon-dynamodb-transactions/ for more info.

**Comment by bosskmk** [comment]
I think I need a transactionManager for javascript.

When there are multiple services implemented as queries rather than existing transactions, you should be able to start, commit, and rollback transactions externally without modifying them.
